config/routes.rb
# Frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/screenings/new', to: 'screenings#new', as: 'screenings_new'
  post '/screenings', to: 'screenings#create', as: 'screenings_create'
  # resources :cinemas, only: %i[] do
  #   resources :screenings, only: %i[] do
  #     resources :books, only: %i[]
  #   end
  # end
  resources :screenings, only: %i[] do
    resources :books, only: %i[new create]
  end
  get 'booking_confirmation/:id', to: 'books#confirmation', as: :booking_confirmation
  resources :users, only: %i[new index create]
  resources :movies, only: %i[show index new edit create update]
  resources :cinemas, only: %i[show index new edit create update] do
    resources :books, only: %i[]
  end
  resources :books, only: %i[index]
  match '*path', to: 'application#route_not_found', via: :all
end

app/controllers/static_pages_controller.rb
# Frozen_string_literal: true

# This class represent the Static Pages on the app.
class StaticPagesController < ApplicationController
  before_action :require_login, except: %i[index]
  before_action :admin_only, except: %i[index]

  def index
    if !admin?
      @cinemas = Cinema.all
      @users_in_cinemas = {}

      if current_user
        @bookings = Booking.includes(screening: [{ cinema: :movies }])
                           .where(user_id: current_user.id)
                           .order(created_at: :desc)
                           .page(params[:page]).per(3)
        @user_bookings_cinema_ids = current_user.bookings.pluck(:screening_id).map { |screening_id| Screening.find(screening_id).cinema_id }.uniq
      end
      @cinemas = Cinema.all
      @cinemas.each do |cinema|
        screenings_with_bookings = cinema.screenings.includes(:bookings)
        users_for_screenings = screenings_with_bookings.map { |screening| screening.bookings.map(&:user) }.flatten.uniq
        @users_in_cinemas[cinema] = users_for_screenings
      end

    else
      @cinema_count = Cinema.count
      @bookings_count = Booking.count
      @cinemas_with_bookings_count = Cinema.joins(:screenings => :bookings).distinct.count

      @cinemas = Cinema.includes(:screenings => { :bookings => :user }).distinct
    end
  end

  private

  def admin_only
    unless admin?
      flash[:danger] = 'Access denied. You must be an admin to perform this action.'
      redirect_to login_path
    end
  end

  def require_login
    unless logged_in?
      flash[:danger] = 'Please log in to book a screening.'
      redirect_to login_path
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/index.html.erb
<% provide(:title, custom_title()) %>
<div class="container">
<h2 class="alert alert-info">"Embrace the Movie Magic: Discover Your Exciting Cinema Bookings"</h2>
<% if !admin? %>
  <% if current_user %>
    <h1>My Bookings</h1>
    <% @bookings.each do |booking| %>
      <div class="book-user-box">
        <h2>Cinema: <%= booking.screening.cinema.name.titleize %></h2>
        <h3>Movie: <%= booking.screening.movie.title.titleize %></h3>
        <p>Date: <%= booking.screening.date %></p>
        <p>Seat Number: <%= booking.seat_number %>
        <p>Time Slot: <%= booking.time_slot %></p>
      </div>
    <% end %>
    <%= paginate @bookings %>
  <% end %>
    <h1>Dashboard</h1>
    <div class="row">
      <% @cinemas.each do |cinema| %>
        <% screenings_with_bookings = cinema.screenings.includes(:bookings) %>
        <div class="col-md-4" style="display: <%= @a = screenings_with_bookings.count > 0 ? 'inline-block;' : 'none;' %>">
          <div class="cinema-box" >
            <h2><%= cinema.name.titleize %></h2>
              <!-- DISPLAY CINEMA WITH BOOKINGS-->
              <% if screenings_with_bookings.any? %>
                <h3>Screenings:</h3>
                <ul>
                  <% @a=cinema.bookings.count == 10 ? 0 : 1 %>
                  <p class="cinema-status" style="color:<%= @a.positive? ? 'green;' : 'red;' %>"><%= @a.positive? ? 'Available' : 'Fully Booked' %></p>
                  <% screenings_with_bookings.each do |screening| %>
                    
                      <%= screening.movie.title.titleize %> - <%= screening.date %> - <%= screening.time_slot %>
                      <!--DISPLAY INFO OF USER WHO SEAT -->
                      <% if admin? %>
                        <% screening.bookings.each do |booking| %>
                          <p>Booking ID: <%= booking.id %>, User: <%= booking.user.full_name.titleize %>, Screening ID: <%= screening.id %></p>
                        <% end %>
                      <% else %>
                      : Currently <%= pluralize(screening.bookings.count, 'seat') %> 
                      <% end %>
                      <!-- Link to create a new book for this screening -->
                      <% if cinema.bookings.count == 10 %>
                        <p style="color:red;">Close</p>
                      <% else %>
                        <%= link_to "Join the Cinema Experience! Click Here!", new_screening_book_path(screening_id: screening.id, cinema_id: cinema.id), class: "new-booking-link" %>
                      <% end %>
                  <% end %>
                  </ul>
              <% else %>
                <p>No screenings with bookings for this cinema.</p>
              <% end %>
            <% if admin? %>
              <h3>Users who made bookings:</h3>
              <ul>
                <% @users_in_cinemas[cinema].each do |user| %>
                  <li><%= user.full_name.titleize %> - <%= user.email %></li>
                <% end %>
              </ul>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
<% else %>
  <h1>Admin Dashboard</h1>

  <p>Total number of registered cinemas: <%= @cinema_count %></p>
  <p>Total number of bookings: <%= @bookings_count %></p>
  <p>Number of cinemas with bookings: <%= @cinemas_with_bookings_count %></p>

  <% @cinemas.each do |cinema| %>
    <div class="cinema-box" style="display: <%= @a=cinema.screenings.count > 0 ? 'inline-block;' : 'none;'%>">
      <h2 class="cinema-name"><%= cinema.name.titleize %></h2>
      <% cinema.screenings.each do |screening| %>
        <div class="screening-details">
          <h3 class="movie-title">Movie: <%= screening.movie.title.titleize %></h3>
          <p>Date: <%= screening.date %></p>
          <p>Time Slot: <%= screening.time_slot %></p>
          <ul class="booking-list">
            <p>Currently <%= pluralize(screening.bookings.count, 'seat') %> at this time.</p>
            <% screening.bookings.each do |booking| %>
              <li class="booking-item">
                <span class="user-info">#<%= booking.seat_number %></span>
                <span class="user-info"><%= booking.user.full_name.titleize %></span>
                <span class="user-info"><%= booking.user.email %></span>
              </li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  <% end %>

<% end %>