config/routes.rb
# Frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/screenings/new', to: 'screenings#new', as: 'screenings_new'
  post '/screenings', to: 'screenings#create', as: 'screenings_create'
  # resources :cinemas, only: %i[] do
  #   resources :screenings, only: %i[] do
  #     resources :books, only: %i[]
  #   end
  # end
  resources :screenings, only: %i[] do
    resources :books, only: %i[new create]
  end
  get 'booking_confirmation/:id', to: 'books#confirmation', as: :booking_confirmation
  resources :users, only: %i[new index create]
  resources :movies, only: %i[show index new edit create update]
  resources :cinemas, only: %i[show index new edit create update] do
    resources :books, only: %i[]
  end
  resources :books, only: %i[index]
  match '*path', to: 'application#route_not_found', via: :all
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger" role="alert"> The form contains <%= pluralize(object.errors.count, 'error') %> </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-primary bg-gradient">
  <p><span>MovieMagic</span>: Your Ultimate Cinema Booking Experience</p>
</footer>

app/views/shared/_jumbotron.html.erb
<div class="bg-light p-5 rounded-lg m-3 jumbotron">
  <h1 class="display-4">Book, Enjoy, Repeat!</h1>
  <p class="lead">"Welcome to our Cinema Booking App! Explore an incredible selection of movies and secure your seats for an unforgettable cinematic experience. Lights, camera, action – let the movie magic begin!"</p>
  <hr class="my-4">
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque nec velit in sapien dictum fermentum. Mauris eget tempor odio.</p>
  <p class="lead">
    <%= link_to 'Unlock the Magic!', login_path, class: 'btn btn-primary btn-lg' %>
  </p>
</div>

app/views/shared/_login.html.erb
<div class="container-fluid h-custom">
  <div class="row d-flex justify-content-center align-items-center h-100">
    <div class="col-md-9 col-lg-6 col-xl-5">
      <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp" class="img-fluid" alt="Login to MovieMagic">
    </div>
    <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1 signin-form">
      <%= form_for(:session, url: login_path) do |f| %>
        <div class="d-flex flex-row align-items-center justify-content-center justify-content-lg-start">
          <p class="login_text lead fw-normal mb-0 me-3">Sign in to continue</p>
        </div>
        <!-- Email input -->
        <div class="input-field-signin">
          <%= f.label :email, class: 'form-label' %>
          <%= f.text_field :email, class: 'form-control form-control-lg', placeholder: 'Enter a valid email address', autofocus: true %>
        </div>
        <!-- Password input -->
        <div class="input-field-signin">
          <label class="form-label" for="form3Example4"></label>
          <%= f.label :password, class: 'form-label' %>
          <%= f.password_field :password, placeholder: 'Enter a valid email address', class: 'form-control form-control-lg', placeholder: 'Enter password' %>
        </div>
        <div class="d-flex justify-content-between align-items-center">
          <!-- Checkbox -->
          <%# <div class="form-check mb-0">
            <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3" />
            <label class="form-check-label" for="form2Example3"> Remember me </label>
          </div> %>
          <%# <a href="#!" class="text-body">Forgot password?</a> %>
        </div>
        <div class="text-right text-lg-start mt-4 pt-2">
          <button type="submit" class="btn btn-primary btn-lg input-field-signin" style="padding-left: 2.5rem; padding-right: 2.5rem;">Login</button>
          <p class="input-field-signin">Don't have an account? <%= link_to 'Register', signup_path, class: 'link-primary' %></p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-lg bg-light navbar-static-top">
  <div class="container-fluid">
    <!-- LOGO -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">MovieMagic</a>
    </div>
    <!-- buttons for cinemas and movies -->
    <ul class="nav navbar-nav">
        <li><%= link_to 'Cinemas', cinemas_path, class: "nav-link" %></li>
        <li> <%= link_to 'Movies', movies_path, class: "nav-link" %> </li>
      <% if admin? %>
        <li> <%= link_to 'Bookings', books_path, class: "nav-link" %> </li>
        <li> <%= link_to 'Screenings', screenings_new_path, class: "nav-link" %> </li>
      <% end %>
    </ul>
      <ul class="nav navbar-nav navbar-right">
<% if request.path == root_path && !current_user %>
        <li><%= link_to 'Login', login_path, class: 'btn btn-primary' %></li>
<% else %>
  <% if current_user %>
        <li><%= link_to "Log out", logout_path, method: :delete, class: "btn btn-primary" %></li>
      </ul>
  <% end %>
<% end %>
    </div>
  </div>
</nav>
<%# 
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav> %>