config/routes.rb
# Frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/screenings/new', to: 'screenings#new', as: 'screenings_new'
  post '/screenings', to: 'screenings#create', as: 'screenings_create'
  # resources :cinemas, only: %i[] do
  #   resources :screenings, only: %i[] do
  #     resources :books, only: %i[]
  #   end
  # end
  resources :screenings, only: %i[] do
    resources :books, only: %i[new create]
  end
  get 'booking_confirmation/:id', to: 'books#confirmation', as: :booking_confirmation
  resources :users, only: %i[new index create]
  resources :movies, only: %i[show index new edit create update]
  resources :cinemas, only: %i[show index new edit create update] do
    resources :books, only: %i[]
  end
  resources :books, only: %i[index]
  match '*path', to: 'application#route_not_found', via: :all
end

app/controllers/books_controller.rb
# Frozen_string_literal: true

# This class represent the bookings of the app.
class BooksController < ApplicationController
  before_action :require_login, except: %i[]
  before_action :admin_only, except: %i[new create]

  def index
    @book = Booking.all.order(created_at: :desc).page(params[:page]).per(10)
  end

  def new
    # In your controller action
    @cinema = Cinema.find(params[:cinema_id])
    @movies = @cinema.movies

    @movie_seat_counts = {}
    @movies.each do |movie|
      @movie_seat_counts[movie.id] = {}
      movie.screenings.each do |screening|
        booked_seats = Booking.where(screening_id: screening.id).pluck(:seat_number)
        available_seats = (1..10).to_a - booked_seats
        @movie_seat_counts[movie.id][screening.time_slot] = available_seats.count
      end
    end

    @screening = Screening.find(params[:screening_id])
    @booking = Booking.new
  end

  def create
    @screening = Screening.find(params[:screening_id])
    @booking = @screening.bookings.build(booking_params)
    @booking.user_id = current_user.id

    if @booking.valid? && @booking.save
      flash[:success] = 'Your booking has been save'
      redirect_to root_url
    else
      render :new
    end
  end

  protected

  def screening_available?(screening)
    screening.cinema.bookings.count < 10
  end

  def admin_only
    unless admin?
      flash[:danger] = "Access denied. You must be an admin to perform this action."
      redirect_to login_path
    end
  end

  def require_login
    unless logged_in?
      flash[:danger] = "Please log in to book a screening."
      redirect_to login_path
    end
  end

  def booking_params
    params.require(:booking).permit(:seat_number, :time_slot)
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def convert_time_to_hh_mm_ss_ampm(time_string)
    # Parse the time string to get the hour and AM/PM
    hour, am_pm = time_string.split

    # Convert to 24-hour format
    hour = am_pm.downcase == 'pm' ? hour.to_i + 12 : hour.to_i
 
    # Format the time as 'HH:MM:SS AM/PM'
    time = Time.new(1970, 1, 1, hour, 0, 0)
    time.strftime('%I:%M:%S %p')
  end

  def booking_error_messages(booking)
    if booking.errors.any?
      booking.errors.full_messages.to_sentence
    else
      'The cinema is fully booked for this screening.'
    end
  end
end

app/views/books/confirmation.html.erb
<h1>Booking Confirmation</h1>
<p>Your booking with ID: <%= @booking.id %> has been successfully confirmed!</p>
<p>Screening Details:</p>
<p>Title: <%= @screening.movie.title %></p>
<p>Date: <%= @screening.date %></p>
<p>Time Slot: <%= @screening.time_slot %></p>

app/views/books/index.html.erb
<% provide(:title, custom_title('Bookings')) %>
<div class="container">

<% if admin? %>
  <h1>Bookings</h1>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Time Slot</th>
        <th>Seat Number</th>
        <th>Movie Name</th>
        <th>Cinema</th>
        <th>Created At</th>
      </tr>
    </thead>
    <tbody>
      <% @book.each do |book| %>
        <tr>
          <td><%= book.user.full_name.titleize %></td>
          <td><%= book.user.email %>
          <td><%= book.time_slot %></td>
          <td><%= book.seat_number %></td>
          <td><%= book.screening.movie.title.titleize %>
          <td><%= book.screening.cinema.name.titleize %></td>
          <td><%= book.created_at.to_formatted_s(:short) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<%= paginate @book %>
</div>

app/views/books/new.html.erb
<% provide(:title, custom_title("Bookings")) %>

<div class="container-fluid h-custom">
  <div class="row d-flex justify-content-center align-items-center h-100">
    <%= form_with model: @booking, url: screening_books_path(@screening, cinema_id: @cinema.id) do |form| %>
      <%= render 'shared/error_messages', object: @booking %>
      <h2>Screening Details</h2>
      <p>Title: <%= @screening.movie.title %></p>
      <p>Date: <%= @screening.date %></p>

      <% available_seats = @movie_seat_counts[@screening.movie.id][@screening.time_slot] || 0 %>
      <p>Available Seats: <%= available_seats %></p>

      <%= form.label :seat_number %>
      <% taken_seats = current_user.bookings.where(screening_id: @screening.cinema.screenings.pluck(:id)).pluck(:seat_number) %>
      <% available_seats = (1..10).to_a - taken_seats %>
      <% screening_taken_seats = @screening.bookings.pluck(:seat_number) %>
      <% available_seats -= screening_taken_seats %>
      <%= form.select :seat_number, options_for_select(available_seats), {}, class: '' %>

      <%= form.label :time_slot %>
      <%= form.select :time_slot, Booking.time_slots.keys, {}, class: '' %>
      
      <%= form.hidden_field :screening_id, value: @screening.id %>
      
      <%= form.submit "Book Now", class: "book-now-button" %>
    <% end %>
    <div class="col-md-9 col-lg-6 col-xl-5">
      <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp" class="img-fluid" alt="Login to MovieMagic">
    </div>
  </div>
</div>

app/views/books/show.html.erb
<% provide(:title, custom_title('Bookings')) %>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Cinema Name</th>
      <th>Movie Name</th>
      <th>Users' Full Name</th>
      <th>Date</th>
      <th>Time</th>
    </tr>
  </thead>
  <tbody>
    <% @booking.each do |book|%>
    <tr>
      <td><%= book.cinema.name %></td>
      <td><%= book.movie.name %></td>
      <td><%= book.user.full_name %>
      <td><%= book.date %></td>
      <td><%= book.time %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @booking %>