config/routes.rb
# Frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/screenings/new', to: 'screenings#new', as: 'screenings_new'
  post '/screenings', to: 'screenings#create', as: 'screenings_create'
  # resources :cinemas, only: %i[] do
  #   resources :screenings, only: %i[] do
  #     resources :books, only: %i[]
  #   end
  # end
  resources :screenings, only: %i[] do
    resources :books, only: %i[new create]
  end
  get 'booking_confirmation/:id', to: 'books#confirmation', as: :booking_confirmation
  resources :users, only: %i[new index create]
  resources :movies, only: %i[show index new edit create update]
  resources :cinemas, only: %i[show index new edit create update] do
    resources :books, only: %i[]
  end
  resources :books, only: %i[index]
  match '*path', to: 'application#route_not_found', via: :all
end

app/models/cinema.rb
# == Schema Information
#
# Table name: cinemas
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Cinema < ApplicationRecord
  has_many :screenings
  has_many :movies, through: :screenings
  has_many :bookings, through: :screenings

  validates :name, presence: true, length: { minimum: 2, maximum: 100 }
end

app/controllers/cinemas_controller.rb
# Frozen_string_literal: true

# This class represent the cinemas in the app.
class CinemasController < ApplicationController
  before_action :require_login, except: %i[index show]
  before_action :admin_only, except: %i[index show]

  def index
    @cinemas = Cinema.all.order(created_at: :desc).page(params[:page]).per(10)
  end

  def new
    @cinema = Cinema.new
  end

  def create
    @cinema = Cinema.new(cinema_params)
    if @cinema.save
      flash[:success] = 'New Cinema has been save.'
      redirect_to cinema_path(@cinema)
    else
      render :new
    end
  end

  def show
    # @movie = Movie.find(params[:movie_id]) if params[:movie_id]
    @cinema = Cinema.find(params[:id])
  end

  def edit
    @cinema = Cinema.find(params[:id])
  end

  def update
    @cinema = Cinema.find(params[:id])
    if @cinema.update(cinema_params)
      flash[:success] = "#{@cinema.name} has been updated"
      redirect_to cinema_path(@cinema)
    else
      render :edit
    end
  end

  private

  def admin_only
    unless admin?
      flash[:danger] = "Access denied. You must be an admin to perform this action."
      redirect_to login_path
    end
  end

  def require_login
    unless logged_in?
      flash[:danger] = "Please log in to book a screening."
      redirect_to login_path
    end
  end

  def cinema_params
    params.require(:cinema).permit(:name)
  end
end

app/helpers/cinemas_helper.rb
module CinemasHelper
end

app/views/cinemas/edit.html.erb
<% provide(:title, custom_title(@cinema.name, 'Modify')) %>
<div class="container-fluid h-custom">
  <div class="row d-flex justify-content-center align-items-center h-100">
    <h1>Editing <%= @cinema.name %></h1>
    <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
      <%= form_for [@cinema] do |f| %>
        <%= render 'shared/error_messages', object: @cinema %>
        <!-- Full name input -->
        <div class="row mb-4">
          <%= f.label :name, class: 'col-sm-4 col-form-label' %>
          <div class="col-sm-8">
            <%= f.text_field :name, class: 'form-control', placeholder: '' %>
          </div>
        </div>
        
        <div class="text-center text-lg-start mt-4 pt-2">
          <button type="submit" class="btn btn-primary btn-lg" style="padding-left: 2.5rem; padding-right: 2.5rem;">Update <%= @cinema.name %></button>
        </div>
      <% end %>
    </div>
    <div class="col-md-9 col-lg-6 col-xl-5">
      <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp" class="img-fluid" alt="Login to MovieMagic">
    </div>
  </div>
</div>

app/views/cinemas/index.html.erb
<% provide(:title, custom_title('Cinemas')) %>
<div class="container">
  <h1>Cinemas</h1>
    <% if admin?  %>
    <%= link_to 'New Cinema', new_cinema_path, class: 'btn btn-primary' %>
    <% end %>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Created At</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @cinemas.each do |cinema| %>
        <tr>
          <td><%= cinema.name %></td>
          <td><%= cinema.created_at.to_formatted_s(:short) %></td>
          <td>
            <%= link_to 'View', cinema_path(cinema), class: 'btn btn-success' %>
            <% if admin? %>
            <%= link_to 'Edit', edit_cinema_path(cinema), class: 'btn btn-warning' %>
            <% end %>
          </td>
        </tr>
        <% end %>
      <tbody>
    </table>
  <%= paginate @cinemas %>
</div>

app/views/cinemas/new.html.erb
<% provide(:title, custom_title('New Cinema')) %>
<div class="container-fluid h-custom">
  <div class="row d-flex justify-content-center align-items-center h-100">
    <h1>New Cinema</h1>
    <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
      <%= form_for(@cinema) do |f| %>
        <%= render 'shared/error_messages', object: @cinema %>
        <!-- Full name input -->
        <div class="row mb-4">
          <%= f.label :name, class: 'col-sm-4 col-form-label' %>
          <div class="col-sm-8">
            <%= f.text_field :name, class: 'form-control', placeholder: '' %>
          </div>
        </div>
        <div class="text-center text-lg-start mt-4 pt-2">
          <button type="submit" class="btn btn-primary btn-lg" style="padding-left: 2.5rem; padding-right: 2.5rem;">Create new cinema</button>
        </div>
      <% end %>
    </div>
    <div class="col-md-9 col-lg-6 col-xl-5">
      <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp" class="img-fluid" alt="Login to MovieMagic">
    </div>
  </div>
</div>

app/views/cinemas/show.html.erb
<% provide(:title, custom_title(@cinema.name)) %>
<div class="row">
  <div class="col-md-4">
  </div>
  <div class="col-md-4">
    <h1>Cinema: <%= @cinema.name %></h1>
    <div class="d-flex flex-column align-items-end">
      <% if admin? %>
      <%= link_to "Edit", edit_cinema_path(@cinema), class: 'btn btn-primary' %>
      <% end %>
    </div>
    <p>Cinema Name: <%= @cinema.name %></p>
  </div>
  <div class="col-md-4">
  </div>
</div>